version: "2"

services:
  cockpit:
    image: markdegroot/cockpit-ubuntu:latest
    container_name: cockpit
    privileged: true
    restart: always
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    labels:
      - "traefik.http.routers.cockpit.rule=Host(`cockpit.homelab.local`)"

networks:
  default:
    external:
      name: homelab-net
