version: '2.0'

# After launching this file, change the admin password
# by shelling into the container and running 
# seafile-server-latest/reset-admin.sh

# After logging in to the web interface, change the
# SERVICE_URL and FILE_SERVER_ROOT

services:
  seafile-db:
    image: mariadb:10.5
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=db_dev
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - /data/seafile/mysql-db:/var/lib/mysql
    restart: unless-stopped

  memcached:
    image: memcached:1.5.6
    container_name: memcached
    entrypoint: memcached -m 256
    restart: unless-stopped

  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    volumes:
      - /data/seafile/file-data:/shared
    environment:
      - DB_HOST=seafile-db
      - DB_ROOT_PASSWD=db_dev
      - TIME_ZONE=US/Central  # set to your local time zone
      - SEAFILE_ADMIN_EMAIL=georgeflug@gmail.com
      - SEAFILE_ADMIN_PASSWORD=changeme
      - SEAFILE_SERVER_LETSENCRYPT=false
      - SEAFILE_SERVER_HOSTNAME=seafile.homelab.local
    depends_on:
      - seafile-db
      - memcached
    labels:
      - "traefik.http.routers.seafile.rule=Host(`seafile.homelab.local`)"
      - "traefik.http.services.seafile.loadbalancer.server.port=80"
    restart: unless-stopped

networks:
  default:
    external:
      name: homelab-net
