version: "2"

services:
  whoami:
    image: containous/whoami
    container_name: whoami
    restart: always
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.homelab.local`)"

networks:
  default:
    external:
      name: homelab-net
